### ISSUE TITLE
Add license type to repo

### ISSUE THREAD

**Issue by joekieffer** [SamuelTS/SketchUp-Universal-Importer-Plugin#13]
Please add copyright information and/or license terms to the README or a COPYRIGHT and/or COPYING file. I looked on the SketchUcation site and this looks to be GPL 3 but it's unclear if that code is the same as the released code from this repo or some modification.

**Comment by SamuelTallet** [comment]
This is the same code that is released on SketchUcation and GitHub. The latter may be in advance... but in both cases the same license applies: GPL 3.

This license did not appear clearly on the repository because the _LICENSE_ file was in the _docs_ subfolder 😜

I also just added a License section in the README and created a _COPYRIGHT_ file at the root of the repository.

**Comment by joekieffer** [comment]
Thanks thats was what I looking for.
