### ISSUE TITLE
Error: Failed to load STEP file: IFC: Unrecognized file schema: CONFIG_CONTROL_DESIGN

### ISSUE THREAD

**Issue by apodsim** [SamuelTS/SketchUp-Universal-Importer-Plugin#9]
I found your SketchUp plugin based on a thread in the SketchUp forums and was glad to see see that STP file format was supported. After installation, I attempted to import a STP and received a
> Universal Importer Error: Command failed:

![Screenshot 2022-08-20 135308](https://user-images.githubusercontent.com/79287485/185762189-967a7e78-1078-43c7-a3a6-a1d0419d4de9.jpg)
Please advise if there is issue with my installation, if possible.

**Comment by SamuelTallet** [comment]
It's not an issue with your installation. This error (DXF: no data blocks loaded) comes from Assimp (which is the program used internally by Universal Importer to convert models). It seems to be fixed in Assimp v5.2.0.

The current version of Universal Importer (v1.1.9) uses Assimp v5.1.6. Once I recompile and upgrade Assimp in Universal Importer, the compatibility with STEP files (among others) will be better 🙂 You'll get a notification.

**Comment by apodsim** [comment]
Thanks for the prompt reply 😃

**Comment by SamuelTallet** [comment]
@apodsim Could you send me a link to download your STP file? I would like to test it with current Universal Importer beta version.

**Comment by apodsim** [comment]
See attached .stp file I was using.

**Comment by SamuelTallet** [comment]
@apodsim I don't see your attachment on GitHub, so I just sent you an email...

**Comment by apodsim** [comment]
I do not understand why as the message reply shows the file is attached.  Please send me your email address as GitHub is blocking the attachement.

**Comment by SamuelTallet** [comment]
@apodsim
I tested your _e1pbxss.stp_ file with current plugin beta. Import fails with a different error:
> ERROR: Failed to load file: IFC: Unrecognized file schema: CONFIG_CONTROL_DESIGN

**Comment by SamuelTallet** [comment]
@apodsim
I tested your _e1pbxss.stp_ file with current plugin beta. Import fails with a different error:

> ERROR: Failed to load file: IFC: Unrecognized file schema: CONFIG_CONTROL_DESIGN

**Comment by apodsim** [comment]
I know the file you were sent is a valid .stp file as I was able to import into Autodesk Inventor and then Export as a .SAT. I use a ACIS to SketchUp converter by SimLab.

**Comment by SamuelTallet** [comment]
Yes, your _.stp_ file is valid. We now have to wait for a fix from the Assimp team...

**Comment by apodsim** [comment]
Has there been any update on the Universal Importer?

**Comment by SamuelTallet** [comment]
Nothing new about the STEP format.

**Comment by SamuelTallet** [comment]
A fix is coming 🙂

**Comment by SamuelTallet** [comment]
Hello,

I was finally able to import your *e1pbxss.stp* file with 1.2.5 version of the Universal Importer plugin, released a few hours ago.

![e1pbxss](https://github.com/user-attachments/assets/b82519fb-083a-41ef-b99c-ccc668e69f38)

PS: My plugin now uses Mayo instead of Assimp to import STEP files.
